/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisualNeurips2025RouteImport } from './routes/visual/neurips-2025'
import { Route as TechElectricRouteImport } from './routes/tech/electric'
import { Route as TechCloudflareRouteImport } from './routes/tech/cloudflare'
import { Route as ResearchHowToTrainModelToRecognizeNextActionRouteImport } from './routes/research/how-to-train-model-to-recognize-next-action'
import { Route as LibEffectRouteImport } from './routes/lib/effect'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiPapersRouteImport } from './routes/api/papers'
import { Route as ApiChatThreadsRouteImport } from './routes/api/chat-threads'
import { Route as ApiChatMessagesRouteImport } from './routes/api/chat-messages'
import { Route as ReposTrycuaCuaRouteImport } from './routes/repos/trycua/cua'
import { Route as ReposSamuiBuildSamuiWalletRouteImport } from './routes/repos/samui-build/samui-wallet'
import { Route as ReposRyanssennTorchlessRouteImport } from './routes/repos/ryanssenn/torchless'
import { Route as ReposPqrsOrgKarabinerElementsRouteImport } from './routes/repos/pqrs-org/Karabiner-Elements'
import { Route as ReposMlExploreMlxRouteImport } from './routes/repos/ml-explore/mlx'
import { Route as ReposKarpathyNanochatRouteImport } from './routes/repos/karpathy/nanochat'
import { Route as ReposJaxMlJaxRouteImport } from './routes/repos/jax-ml/jax'
import { Route as ReposGardenCoJazzRouteImport } from './routes/repos/garden-co/jazz'
import { Route as ReposEarendilWorksAbsurdRouteImport } from './routes/repos/earendil-works/absurd'
import { Route as ReposAnthropicsClaudeAgentSdkPythonRouteImport } from './routes/repos/anthropics/claude-agent-sdk-python'
import { Route as ReposSmerityShaRnnRouteImport } from './routes/repos/Smerity/sha-rnn'
import { Route as ReposMizuhoAOKIJaxGenerativeModelsRouteImport } from './routes/repos/MizuhoAOKI/jax-generative-models'
import { Route as Papers25DeepseekV32RouteImport } from './routes/papers/25/deepseek-v3-2'
import { Route as ExplainMlTransformerRouteImport } from './routes/explain/ml/transformer'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiChatMutationsRouteImport } from './routes/api/chat/mutations'
import { Route as ApiChatAiRouteImport } from './routes/api/chat/ai'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualNeurips2025Route = VisualNeurips2025RouteImport.update({
  id: '/visual/neurips-2025',
  path: '/visual/neurips-2025',
  getParentRoute: () => rootRouteImport,
} as any)
const TechElectricRoute = TechElectricRouteImport.update({
  id: '/tech/electric',
  path: '/tech/electric',
  getParentRoute: () => rootRouteImport,
} as any)
const TechCloudflareRoute = TechCloudflareRouteImport.update({
  id: '/tech/cloudflare',
  path: '/tech/cloudflare',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchHowToTrainModelToRecognizeNextActionRoute =
  ResearchHowToTrainModelToRecognizeNextActionRouteImport.update({
    id: '/research/how-to-train-model-to-recognize-next-action',
    path: '/research/how-to-train-model-to-recognize-next-action',
    getParentRoute: () => rootRouteImport,
  } as any)
const LibEffectRoute = LibEffectRouteImport.update({
  id: '/lib/effect',
  path: '/lib/effect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPapersRoute = ApiPapersRouteImport.update({
  id: '/api/papers',
  path: '/api/papers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatThreadsRoute = ApiChatThreadsRouteImport.update({
  id: '/api/chat-threads',
  path: '/api/chat-threads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatMessagesRoute = ApiChatMessagesRouteImport.update({
  id: '/api/chat-messages',
  path: '/api/chat-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposTrycuaCuaRoute = ReposTrycuaCuaRouteImport.update({
  id: '/repos/trycua/cua',
  path: '/repos/trycua/cua',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposSamuiBuildSamuiWalletRoute =
  ReposSamuiBuildSamuiWalletRouteImport.update({
    id: '/repos/samui-build/samui-wallet',
    path: '/repos/samui-build/samui-wallet',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReposRyanssennTorchlessRoute = ReposRyanssennTorchlessRouteImport.update({
  id: '/repos/ryanssenn/torchless',
  path: '/repos/ryanssenn/torchless',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposPqrsOrgKarabinerElementsRoute =
  ReposPqrsOrgKarabinerElementsRouteImport.update({
    id: '/repos/pqrs-org/Karabiner-Elements',
    path: '/repos/pqrs-org/Karabiner-Elements',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReposMlExploreMlxRoute = ReposMlExploreMlxRouteImport.update({
  id: '/repos/ml-explore/mlx',
  path: '/repos/ml-explore/mlx',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposKarpathyNanochatRoute = ReposKarpathyNanochatRouteImport.update({
  id: '/repos/karpathy/nanochat',
  path: '/repos/karpathy/nanochat',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposJaxMlJaxRoute = ReposJaxMlJaxRouteImport.update({
  id: '/repos/jax-ml/jax',
  path: '/repos/jax-ml/jax',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposGardenCoJazzRoute = ReposGardenCoJazzRouteImport.update({
  id: '/repos/garden-co/jazz',
  path: '/repos/garden-co/jazz',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposEarendilWorksAbsurdRoute =
  ReposEarendilWorksAbsurdRouteImport.update({
    id: '/repos/earendil-works/absurd',
    path: '/repos/earendil-works/absurd',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReposAnthropicsClaudeAgentSdkPythonRoute =
  ReposAnthropicsClaudeAgentSdkPythonRouteImport.update({
    id: '/repos/anthropics/claude-agent-sdk-python',
    path: '/repos/anthropics/claude-agent-sdk-python',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReposSmerityShaRnnRoute = ReposSmerityShaRnnRouteImport.update({
  id: '/repos/Smerity/sha-rnn',
  path: '/repos/Smerity/sha-rnn',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposMizuhoAOKIJaxGenerativeModelsRoute =
  ReposMizuhoAOKIJaxGenerativeModelsRouteImport.update({
    id: '/repos/MizuhoAOKI/jax-generative-models',
    path: '/repos/MizuhoAOKI/jax-generative-models',
    getParentRoute: () => rootRouteImport,
  } as any)
const Papers25DeepseekV32Route = Papers25DeepseekV32RouteImport.update({
  id: '/papers/25/deepseek-v3-2',
  path: '/papers/25/deepseek-v3-2',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainMlTransformerRoute = ExplainMlTransformerRouteImport.update({
  id: '/explain/ml/transformer',
  path: '/explain/ml/transformer',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatMutationsRoute = ApiChatMutationsRouteImport.update({
  id: '/api/chat/mutations',
  path: '/api/chat/mutations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatAiRoute = ApiChatAiRouteImport.update({
  id: '/api/chat/ai',
  path: '/api/chat/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat-messages': typeof ApiChatMessagesRoute
  '/api/chat-threads': typeof ApiChatThreadsRoute
  '/api/papers': typeof ApiPapersRoute
  '/api/users': typeof ApiUsersRoute
  '/lib/effect': typeof LibEffectRoute
  '/research/how-to-train-model-to-recognize-next-action': typeof ResearchHowToTrainModelToRecognizeNextActionRoute
  '/tech/cloudflare': typeof TechCloudflareRoute
  '/tech/electric': typeof TechElectricRoute
  '/visual/neurips-2025': typeof VisualNeurips2025Route
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/ai': typeof ApiChatAiRoute
  '/api/chat/mutations': typeof ApiChatMutationsRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/explain/ml/transformer': typeof ExplainMlTransformerRoute
  '/papers/25/deepseek-v3-2': typeof Papers25DeepseekV32Route
  '/repos/MizuhoAOKI/jax-generative-models': typeof ReposMizuhoAOKIJaxGenerativeModelsRoute
  '/repos/Smerity/sha-rnn': typeof ReposSmerityShaRnnRoute
  '/repos/anthropics/claude-agent-sdk-python': typeof ReposAnthropicsClaudeAgentSdkPythonRoute
  '/repos/earendil-works/absurd': typeof ReposEarendilWorksAbsurdRoute
  '/repos/garden-co/jazz': typeof ReposGardenCoJazzRoute
  '/repos/jax-ml/jax': typeof ReposJaxMlJaxRoute
  '/repos/karpathy/nanochat': typeof ReposKarpathyNanochatRoute
  '/repos/ml-explore/mlx': typeof ReposMlExploreMlxRoute
  '/repos/pqrs-org/Karabiner-Elements': typeof ReposPqrsOrgKarabinerElementsRoute
  '/repos/ryanssenn/torchless': typeof ReposRyanssennTorchlessRoute
  '/repos/samui-build/samui-wallet': typeof ReposSamuiBuildSamuiWalletRoute
  '/repos/trycua/cua': typeof ReposTrycuaCuaRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat-messages': typeof ApiChatMessagesRoute
  '/api/chat-threads': typeof ApiChatThreadsRoute
  '/api/papers': typeof ApiPapersRoute
  '/api/users': typeof ApiUsersRoute
  '/lib/effect': typeof LibEffectRoute
  '/research/how-to-train-model-to-recognize-next-action': typeof ResearchHowToTrainModelToRecognizeNextActionRoute
  '/tech/cloudflare': typeof TechCloudflareRoute
  '/tech/electric': typeof TechElectricRoute
  '/visual/neurips-2025': typeof VisualNeurips2025Route
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/ai': typeof ApiChatAiRoute
  '/api/chat/mutations': typeof ApiChatMutationsRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/explain/ml/transformer': typeof ExplainMlTransformerRoute
  '/papers/25/deepseek-v3-2': typeof Papers25DeepseekV32Route
  '/repos/MizuhoAOKI/jax-generative-models': typeof ReposMizuhoAOKIJaxGenerativeModelsRoute
  '/repos/Smerity/sha-rnn': typeof ReposSmerityShaRnnRoute
  '/repos/anthropics/claude-agent-sdk-python': typeof ReposAnthropicsClaudeAgentSdkPythonRoute
  '/repos/earendil-works/absurd': typeof ReposEarendilWorksAbsurdRoute
  '/repos/garden-co/jazz': typeof ReposGardenCoJazzRoute
  '/repos/jax-ml/jax': typeof ReposJaxMlJaxRoute
  '/repos/karpathy/nanochat': typeof ReposKarpathyNanochatRoute
  '/repos/ml-explore/mlx': typeof ReposMlExploreMlxRoute
  '/repos/pqrs-org/Karabiner-Elements': typeof ReposPqrsOrgKarabinerElementsRoute
  '/repos/ryanssenn/torchless': typeof ReposRyanssennTorchlessRoute
  '/repos/samui-build/samui-wallet': typeof ReposSamuiBuildSamuiWalletRoute
  '/repos/trycua/cua': typeof ReposTrycuaCuaRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat-messages': typeof ApiChatMessagesRoute
  '/api/chat-threads': typeof ApiChatThreadsRoute
  '/api/papers': typeof ApiPapersRoute
  '/api/users': typeof ApiUsersRoute
  '/lib/effect': typeof LibEffectRoute
  '/research/how-to-train-model-to-recognize-next-action': typeof ResearchHowToTrainModelToRecognizeNextActionRoute
  '/tech/cloudflare': typeof TechCloudflareRoute
  '/tech/electric': typeof TechElectricRoute
  '/visual/neurips-2025': typeof VisualNeurips2025Route
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/ai': typeof ApiChatAiRoute
  '/api/chat/mutations': typeof ApiChatMutationsRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/explain/ml/transformer': typeof ExplainMlTransformerRoute
  '/papers/25/deepseek-v3-2': typeof Papers25DeepseekV32Route
  '/repos/MizuhoAOKI/jax-generative-models': typeof ReposMizuhoAOKIJaxGenerativeModelsRoute
  '/repos/Smerity/sha-rnn': typeof ReposSmerityShaRnnRoute
  '/repos/anthropics/claude-agent-sdk-python': typeof ReposAnthropicsClaudeAgentSdkPythonRoute
  '/repos/earendil-works/absurd': typeof ReposEarendilWorksAbsurdRoute
  '/repos/garden-co/jazz': typeof ReposGardenCoJazzRoute
  '/repos/jax-ml/jax': typeof ReposJaxMlJaxRoute
  '/repos/karpathy/nanochat': typeof ReposKarpathyNanochatRoute
  '/repos/ml-explore/mlx': typeof ReposMlExploreMlxRoute
  '/repos/pqrs-org/Karabiner-Elements': typeof ReposPqrsOrgKarabinerElementsRoute
  '/repos/ryanssenn/torchless': typeof ReposRyanssennTorchlessRoute
  '/repos/samui-build/samui-wallet': typeof ReposSamuiBuildSamuiWalletRoute
  '/repos/trycua/cua': typeof ReposTrycuaCuaRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat-messages'
    | '/api/chat-threads'
    | '/api/papers'
    | '/api/users'
    | '/lib/effect'
    | '/research/how-to-train-model-to-recognize-next-action'
    | '/tech/cloudflare'
    | '/tech/electric'
    | '/visual/neurips-2025'
    | '/api/auth/$'
    | '/api/chat/ai'
    | '/api/chat/mutations'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/explain/ml/transformer'
    | '/papers/25/deepseek-v3-2'
    | '/repos/MizuhoAOKI/jax-generative-models'
    | '/repos/Smerity/sha-rnn'
    | '/repos/anthropics/claude-agent-sdk-python'
    | '/repos/earendil-works/absurd'
    | '/repos/garden-co/jazz'
    | '/repos/jax-ml/jax'
    | '/repos/karpathy/nanochat'
    | '/repos/ml-explore/mlx'
    | '/repos/pqrs-org/Karabiner-Elements'
    | '/repos/ryanssenn/torchless'
    | '/repos/samui-build/samui-wallet'
    | '/repos/trycua/cua'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat-messages'
    | '/api/chat-threads'
    | '/api/papers'
    | '/api/users'
    | '/lib/effect'
    | '/research/how-to-train-model-to-recognize-next-action'
    | '/tech/cloudflare'
    | '/tech/electric'
    | '/visual/neurips-2025'
    | '/api/auth/$'
    | '/api/chat/ai'
    | '/api/chat/mutations'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/explain/ml/transformer'
    | '/papers/25/deepseek-v3-2'
    | '/repos/MizuhoAOKI/jax-generative-models'
    | '/repos/Smerity/sha-rnn'
    | '/repos/anthropics/claude-agent-sdk-python'
    | '/repos/earendil-works/absurd'
    | '/repos/garden-co/jazz'
    | '/repos/jax-ml/jax'
    | '/repos/karpathy/nanochat'
    | '/repos/ml-explore/mlx'
    | '/repos/pqrs-org/Karabiner-Elements'
    | '/repos/ryanssenn/torchless'
    | '/repos/samui-build/samui-wallet'
    | '/repos/trycua/cua'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/api/chat-messages'
    | '/api/chat-threads'
    | '/api/papers'
    | '/api/users'
    | '/lib/effect'
    | '/research/how-to-train-model-to-recognize-next-action'
    | '/tech/cloudflare'
    | '/tech/electric'
    | '/visual/neurips-2025'
    | '/api/auth/$'
    | '/api/chat/ai'
    | '/api/chat/mutations'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/explain/ml/transformer'
    | '/papers/25/deepseek-v3-2'
    | '/repos/MizuhoAOKI/jax-generative-models'
    | '/repos/Smerity/sha-rnn'
    | '/repos/anthropics/claude-agent-sdk-python'
    | '/repos/earendil-works/absurd'
    | '/repos/garden-co/jazz'
    | '/repos/jax-ml/jax'
    | '/repos/karpathy/nanochat'
    | '/repos/ml-explore/mlx'
    | '/repos/pqrs-org/Karabiner-Elements'
    | '/repos/ryanssenn/torchless'
    | '/repos/samui-build/samui-wallet'
    | '/repos/trycua/cua'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatMessagesRoute: typeof ApiChatMessagesRoute
  ApiChatThreadsRoute: typeof ApiChatThreadsRoute
  ApiPapersRoute: typeof ApiPapersRoute
  ApiUsersRoute: typeof ApiUsersRoute
  LibEffectRoute: typeof LibEffectRoute
  ResearchHowToTrainModelToRecognizeNextActionRoute: typeof ResearchHowToTrainModelToRecognizeNextActionRoute
  TechCloudflareRoute: typeof TechCloudflareRoute
  TechElectricRoute: typeof TechElectricRoute
  VisualNeurips2025Route: typeof VisualNeurips2025Route
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiChatAiRoute: typeof ApiChatAiRoute
  ApiChatMutationsRoute: typeof ApiChatMutationsRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  ExplainMlTransformerRoute: typeof ExplainMlTransformerRoute
  Papers25DeepseekV32Route: typeof Papers25DeepseekV32Route
  ReposMizuhoAOKIJaxGenerativeModelsRoute: typeof ReposMizuhoAOKIJaxGenerativeModelsRoute
  ReposSmerityShaRnnRoute: typeof ReposSmerityShaRnnRoute
  ReposAnthropicsClaudeAgentSdkPythonRoute: typeof ReposAnthropicsClaudeAgentSdkPythonRoute
  ReposEarendilWorksAbsurdRoute: typeof ReposEarendilWorksAbsurdRoute
  ReposGardenCoJazzRoute: typeof ReposGardenCoJazzRoute
  ReposJaxMlJaxRoute: typeof ReposJaxMlJaxRoute
  ReposKarpathyNanochatRoute: typeof ReposKarpathyNanochatRoute
  ReposMlExploreMlxRoute: typeof ReposMlExploreMlxRoute
  ReposPqrsOrgKarabinerElementsRoute: typeof ReposPqrsOrgKarabinerElementsRoute
  ReposRyanssennTorchlessRoute: typeof ReposRyanssennTorchlessRoute
  ReposSamuiBuildSamuiWalletRoute: typeof ReposSamuiBuildSamuiWalletRoute
  ReposTrycuaCuaRoute: typeof ReposTrycuaCuaRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visual/neurips-2025': {
      id: '/visual/neurips-2025'
      path: '/visual/neurips-2025'
      fullPath: '/visual/neurips-2025'
      preLoaderRoute: typeof VisualNeurips2025RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech/electric': {
      id: '/tech/electric'
      path: '/tech/electric'
      fullPath: '/tech/electric'
      preLoaderRoute: typeof TechElectricRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech/cloudflare': {
      id: '/tech/cloudflare'
      path: '/tech/cloudflare'
      fullPath: '/tech/cloudflare'
      preLoaderRoute: typeof TechCloudflareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/how-to-train-model-to-recognize-next-action': {
      id: '/research/how-to-train-model-to-recognize-next-action'
      path: '/research/how-to-train-model-to-recognize-next-action'
      fullPath: '/research/how-to-train-model-to-recognize-next-action'
      preLoaderRoute: typeof ResearchHowToTrainModelToRecognizeNextActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lib/effect': {
      id: '/lib/effect'
      path: '/lib/effect'
      fullPath: '/lib/effect'
      preLoaderRoute: typeof LibEffectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/papers': {
      id: '/api/papers'
      path: '/api/papers'
      fullPath: '/api/papers'
      preLoaderRoute: typeof ApiPapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-threads': {
      id: '/api/chat-threads'
      path: '/api/chat-threads'
      fullPath: '/api/chat-threads'
      preLoaderRoute: typeof ApiChatThreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-messages': {
      id: '/api/chat-messages'
      path: '/api/chat-messages'
      fullPath: '/api/chat-messages'
      preLoaderRoute: typeof ApiChatMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/trycua/cua': {
      id: '/repos/trycua/cua'
      path: '/repos/trycua/cua'
      fullPath: '/repos/trycua/cua'
      preLoaderRoute: typeof ReposTrycuaCuaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/samui-build/samui-wallet': {
      id: '/repos/samui-build/samui-wallet'
      path: '/repos/samui-build/samui-wallet'
      fullPath: '/repos/samui-build/samui-wallet'
      preLoaderRoute: typeof ReposSamuiBuildSamuiWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/ryanssenn/torchless': {
      id: '/repos/ryanssenn/torchless'
      path: '/repos/ryanssenn/torchless'
      fullPath: '/repos/ryanssenn/torchless'
      preLoaderRoute: typeof ReposRyanssennTorchlessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/pqrs-org/Karabiner-Elements': {
      id: '/repos/pqrs-org/Karabiner-Elements'
      path: '/repos/pqrs-org/Karabiner-Elements'
      fullPath: '/repos/pqrs-org/Karabiner-Elements'
      preLoaderRoute: typeof ReposPqrsOrgKarabinerElementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/ml-explore/mlx': {
      id: '/repos/ml-explore/mlx'
      path: '/repos/ml-explore/mlx'
      fullPath: '/repos/ml-explore/mlx'
      preLoaderRoute: typeof ReposMlExploreMlxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/karpathy/nanochat': {
      id: '/repos/karpathy/nanochat'
      path: '/repos/karpathy/nanochat'
      fullPath: '/repos/karpathy/nanochat'
      preLoaderRoute: typeof ReposKarpathyNanochatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/jax-ml/jax': {
      id: '/repos/jax-ml/jax'
      path: '/repos/jax-ml/jax'
      fullPath: '/repos/jax-ml/jax'
      preLoaderRoute: typeof ReposJaxMlJaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/garden-co/jazz': {
      id: '/repos/garden-co/jazz'
      path: '/repos/garden-co/jazz'
      fullPath: '/repos/garden-co/jazz'
      preLoaderRoute: typeof ReposGardenCoJazzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/earendil-works/absurd': {
      id: '/repos/earendil-works/absurd'
      path: '/repos/earendil-works/absurd'
      fullPath: '/repos/earendil-works/absurd'
      preLoaderRoute: typeof ReposEarendilWorksAbsurdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/anthropics/claude-agent-sdk-python': {
      id: '/repos/anthropics/claude-agent-sdk-python'
      path: '/repos/anthropics/claude-agent-sdk-python'
      fullPath: '/repos/anthropics/claude-agent-sdk-python'
      preLoaderRoute: typeof ReposAnthropicsClaudeAgentSdkPythonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/Smerity/sha-rnn': {
      id: '/repos/Smerity/sha-rnn'
      path: '/repos/Smerity/sha-rnn'
      fullPath: '/repos/Smerity/sha-rnn'
      preLoaderRoute: typeof ReposSmerityShaRnnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/MizuhoAOKI/jax-generative-models': {
      id: '/repos/MizuhoAOKI/jax-generative-models'
      path: '/repos/MizuhoAOKI/jax-generative-models'
      fullPath: '/repos/MizuhoAOKI/jax-generative-models'
      preLoaderRoute: typeof ReposMizuhoAOKIJaxGenerativeModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers/25/deepseek-v3-2': {
      id: '/papers/25/deepseek-v3-2'
      path: '/papers/25/deepseek-v3-2'
      fullPath: '/papers/25/deepseek-v3-2'
      preLoaderRoute: typeof Papers25DeepseekV32RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explain/ml/transformer': {
      id: '/explain/ml/transformer'
      path: '/explain/ml/transformer'
      fullPath: '/explain/ml/transformer'
      preLoaderRoute: typeof ExplainMlTransformerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/mutations': {
      id: '/api/chat/mutations'
      path: '/api/chat/mutations'
      fullPath: '/api/chat/mutations'
      preLoaderRoute: typeof ApiChatMutationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/ai': {
      id: '/api/chat/ai'
      path: '/api/chat/ai'
      fullPath: '/api/chat/ai'
      preLoaderRoute: typeof ApiChatAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatMessagesRoute: ApiChatMessagesRoute,
  ApiChatThreadsRoute: ApiChatThreadsRoute,
  ApiPapersRoute: ApiPapersRoute,
  ApiUsersRoute: ApiUsersRoute,
  LibEffectRoute: LibEffectRoute,
  ResearchHowToTrainModelToRecognizeNextActionRoute:
    ResearchHowToTrainModelToRecognizeNextActionRoute,
  TechCloudflareRoute: TechCloudflareRoute,
  TechElectricRoute: TechElectricRoute,
  VisualNeurips2025Route: VisualNeurips2025Route,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiChatAiRoute: ApiChatAiRoute,
  ApiChatMutationsRoute: ApiChatMutationsRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  ExplainMlTransformerRoute: ExplainMlTransformerRoute,
  Papers25DeepseekV32Route: Papers25DeepseekV32Route,
  ReposMizuhoAOKIJaxGenerativeModelsRoute:
    ReposMizuhoAOKIJaxGenerativeModelsRoute,
  ReposSmerityShaRnnRoute: ReposSmerityShaRnnRoute,
  ReposAnthropicsClaudeAgentSdkPythonRoute:
    ReposAnthropicsClaudeAgentSdkPythonRoute,
  ReposEarendilWorksAbsurdRoute: ReposEarendilWorksAbsurdRoute,
  ReposGardenCoJazzRoute: ReposGardenCoJazzRoute,
  ReposJaxMlJaxRoute: ReposJaxMlJaxRoute,
  ReposKarpathyNanochatRoute: ReposKarpathyNanochatRoute,
  ReposMlExploreMlxRoute: ReposMlExploreMlxRoute,
  ReposPqrsOrgKarabinerElementsRoute: ReposPqrsOrgKarabinerElementsRoute,
  ReposRyanssennTorchlessRoute: ReposRyanssennTorchlessRoute,
  ReposSamuiBuildSamuiWalletRoute: ReposSamuiBuildSamuiWalletRoute,
  ReposTrycuaCuaRoute: ReposTrycuaCuaRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
