/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as UsersRouteImport } from "./routes/users"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as ChatRouteImport } from "./routes/chat"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ApiUsersRouteImport } from "./routes/api/users"
import { Route as ApiChatThreadsRouteImport } from "./routes/api/chat-threads"
import { Route as ApiChatMessagesRouteImport } from "./routes/api/chat-messages"
import { Route as DemoStartServerFuncsRouteImport } from "./routes/demo/start.server-funcs"
import { Route as DemoStartApiRequestRouteImport } from "./routes/demo/start.api-request"
import { Route as DemoApiNamesRouteImport } from "./routes/demo/api.names"
import { Route as ApiChatMutationsRouteImport } from "./routes/api/chat/mutations"
import { Route as ApiChatAiRouteImport } from "./routes/api/chat/ai"
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth/$"
import { Route as DemoStartSsrIndexRouteImport } from "./routes/demo/start.ssr.index"
import { Route as DemoStartSsrSpaModeRouteImport } from "./routes/demo/start.ssr.spa-mode"
import { Route as DemoStartSsrFullSsrRouteImport } from "./routes/demo/start.ssr.full-ssr"
import { Route as DemoStartSsrDataOnlyRouteImport } from "./routes/demo/start.ssr.data-only"

const UsersRoute = UsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: "/chat",
  path: "/chat",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: "/api/users",
  path: "/api/users",
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatThreadsRoute = ApiChatThreadsRouteImport.update({
  id: "/api/chat-threads",
  path: "/api/chat-threads",
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatMessagesRoute = ApiChatMessagesRouteImport.update({
  id: "/api/chat-messages",
  path: "/api/chat-messages",
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: "/demo/start/server-funcs",
  path: "/demo/start/server-funcs",
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: "/demo/start/api-request",
  path: "/demo/start/api-request",
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: "/demo/api/names",
  path: "/demo/api/names",
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatMutationsRoute = ApiChatMutationsRouteImport.update({
  id: "/api/chat/mutations",
  path: "/api/chat/mutations",
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatAiRoute = ApiChatAiRouteImport.update({
  id: "/api/chat/ai",
  path: "/api/chat/ai",
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: "/demo/start/ssr/",
  path: "/demo/start/ssr/",
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: "/demo/start/ssr/spa-mode",
  path: "/demo/start/ssr/spa-mode",
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: "/demo/start/ssr/full-ssr",
  path: "/demo/start/ssr/full-ssr",
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: "/demo/start/ssr/data-only",
  path: "/demo/start/ssr/data-only",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/chat": typeof ChatRoute
  "/login": typeof LoginRoute
  "/users": typeof UsersRoute
  "/api/chat-messages": typeof ApiChatMessagesRoute
  "/api/chat-threads": typeof ApiChatThreadsRoute
  "/api/users": typeof ApiUsersRoute
  "/api/auth/$": typeof ApiAuthSplatRoute
  "/api/chat/ai": typeof ApiChatAiRoute
  "/api/chat/mutations": typeof ApiChatMutationsRoute
  "/demo/api/names": typeof DemoApiNamesRoute
  "/demo/start/api-request": typeof DemoStartApiRequestRoute
  "/demo/start/server-funcs": typeof DemoStartServerFuncsRoute
  "/demo/start/ssr/data-only": typeof DemoStartSsrDataOnlyRoute
  "/demo/start/ssr/full-ssr": typeof DemoStartSsrFullSsrRoute
  "/demo/start/ssr/spa-mode": typeof DemoStartSsrSpaModeRoute
  "/demo/start/ssr": typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/chat": typeof ChatRoute
  "/login": typeof LoginRoute
  "/users": typeof UsersRoute
  "/api/chat-messages": typeof ApiChatMessagesRoute
  "/api/chat-threads": typeof ApiChatThreadsRoute
  "/api/users": typeof ApiUsersRoute
  "/api/auth/$": typeof ApiAuthSplatRoute
  "/api/chat/ai": typeof ApiChatAiRoute
  "/api/chat/mutations": typeof ApiChatMutationsRoute
  "/demo/api/names": typeof DemoApiNamesRoute
  "/demo/start/api-request": typeof DemoStartApiRequestRoute
  "/demo/start/server-funcs": typeof DemoStartServerFuncsRoute
  "/demo/start/ssr/data-only": typeof DemoStartSsrDataOnlyRoute
  "/demo/start/ssr/full-ssr": typeof DemoStartSsrFullSsrRoute
  "/demo/start/ssr/spa-mode": typeof DemoStartSsrSpaModeRoute
  "/demo/start/ssr": typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/chat": typeof ChatRoute
  "/login": typeof LoginRoute
  "/users": typeof UsersRoute
  "/api/chat-messages": typeof ApiChatMessagesRoute
  "/api/chat-threads": typeof ApiChatThreadsRoute
  "/api/users": typeof ApiUsersRoute
  "/api/auth/$": typeof ApiAuthSplatRoute
  "/api/chat/ai": typeof ApiChatAiRoute
  "/api/chat/mutations": typeof ApiChatMutationsRoute
  "/demo/api/names": typeof DemoApiNamesRoute
  "/demo/start/api-request": typeof DemoStartApiRequestRoute
  "/demo/start/server-funcs": typeof DemoStartServerFuncsRoute
  "/demo/start/ssr/data-only": typeof DemoStartSsrDataOnlyRoute
  "/demo/start/ssr/full-ssr": typeof DemoStartSsrFullSsrRoute
  "/demo/start/ssr/spa-mode": typeof DemoStartSsrSpaModeRoute
  "/demo/start/ssr/": typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/chat"
    | "/login"
    | "/users"
    | "/api/chat-messages"
    | "/api/chat-threads"
    | "/api/users"
    | "/api/auth/$"
    | "/api/chat/ai"
    | "/api/chat/mutations"
    | "/demo/api/names"
    | "/demo/start/api-request"
    | "/demo/start/server-funcs"
    | "/demo/start/ssr/data-only"
    | "/demo/start/ssr/full-ssr"
    | "/demo/start/ssr/spa-mode"
    | "/demo/start/ssr"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/chat"
    | "/login"
    | "/users"
    | "/api/chat-messages"
    | "/api/chat-threads"
    | "/api/users"
    | "/api/auth/$"
    | "/api/chat/ai"
    | "/api/chat/mutations"
    | "/demo/api/names"
    | "/demo/start/api-request"
    | "/demo/start/server-funcs"
    | "/demo/start/ssr/data-only"
    | "/demo/start/ssr/full-ssr"
    | "/demo/start/ssr/spa-mode"
    | "/demo/start/ssr"
  id:
    | "__root__"
    | "/"
    | "/chat"
    | "/login"
    | "/users"
    | "/api/chat-messages"
    | "/api/chat-threads"
    | "/api/users"
    | "/api/auth/$"
    | "/api/chat/ai"
    | "/api/chat/mutations"
    | "/demo/api/names"
    | "/demo/start/api-request"
    | "/demo/start/server-funcs"
    | "/demo/start/ssr/data-only"
    | "/demo/start/ssr/full-ssr"
    | "/demo/start/ssr/spa-mode"
    | "/demo/start/ssr/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  LoginRoute: typeof LoginRoute
  UsersRoute: typeof UsersRoute
  ApiChatMessagesRoute: typeof ApiChatMessagesRoute
  ApiChatThreadsRoute: typeof ApiChatThreadsRoute
  ApiUsersRoute: typeof ApiUsersRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiChatAiRoute: typeof ApiChatAiRoute
  ApiChatMutationsRoute: typeof ApiChatMutationsRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/users": {
      id: "/users"
      path: "/users"
      fullPath: "/users"
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/chat": {
      id: "/chat"
      path: "/chat"
      fullPath: "/chat"
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/api/users": {
      id: "/api/users"
      path: "/api/users"
      fullPath: "/api/users"
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/api/chat-threads": {
      id: "/api/chat-threads"
      path: "/api/chat-threads"
      fullPath: "/api/chat-threads"
      preLoaderRoute: typeof ApiChatThreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/api/chat-messages": {
      id: "/api/chat-messages"
      path: "/api/chat-messages"
      fullPath: "/api/chat-messages"
      preLoaderRoute: typeof ApiChatMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/demo/start/server-funcs": {
      id: "/demo/start/server-funcs"
      path: "/demo/start/server-funcs"
      fullPath: "/demo/start/server-funcs"
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/demo/start/api-request": {
      id: "/demo/start/api-request"
      path: "/demo/start/api-request"
      fullPath: "/demo/start/api-request"
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/demo/api/names": {
      id: "/demo/api/names"
      path: "/demo/api/names"
      fullPath: "/demo/api/names"
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/api/chat/mutations": {
      id: "/api/chat/mutations"
      path: "/api/chat/mutations"
      fullPath: "/api/chat/mutations"
      preLoaderRoute: typeof ApiChatMutationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/api/chat/ai": {
      id: "/api/chat/ai"
      path: "/api/chat/ai"
      fullPath: "/api/chat/ai"
      preLoaderRoute: typeof ApiChatAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/api/auth/$": {
      id: "/api/auth/$"
      path: "/api/auth/$"
      fullPath: "/api/auth/$"
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/demo/start/ssr/": {
      id: "/demo/start/ssr/"
      path: "/demo/start/ssr"
      fullPath: "/demo/start/ssr"
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/demo/start/ssr/spa-mode": {
      id: "/demo/start/ssr/spa-mode"
      path: "/demo/start/ssr/spa-mode"
      fullPath: "/demo/start/ssr/spa-mode"
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/demo/start/ssr/full-ssr": {
      id: "/demo/start/ssr/full-ssr"
      path: "/demo/start/ssr/full-ssr"
      fullPath: "/demo/start/ssr/full-ssr"
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/demo/start/ssr/data-only": {
      id: "/demo/start/ssr/data-only"
      path: "/demo/start/ssr/data-only"
      fullPath: "/demo/start/ssr/data-only"
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  LoginRoute: LoginRoute,
  UsersRoute: UsersRoute,
  ApiChatMessagesRoute: ApiChatMessagesRoute,
  ApiChatThreadsRoute: ApiChatThreadsRoute,
  ApiUsersRoute: ApiUsersRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiChatAiRoute: ApiChatAiRoute,
  ApiChatMutationsRoute: ApiChatMutationsRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from "./router.tsx"
import type { createStart } from "@tanstack/react-start"
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
